<?php
if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true) die();

$arComponentParameters = array(
    "GROUPS" => array(
        "SEF_SETTINGS" => array(
            "NAME" => GetMessage("SEF_SETTINGS"),
            "SORT" => 100,
        ),
        "URL_SETTINGS" => array(
            "NAME" => GetMessage("URL_SETTINGS"),
            "SORT" => 200,
        ),
    ),
    "PARAMETERS" => array(
        "SEF_MODE" => array(
            "PARENT" => "SEF_SETTINGS",
            "NAME" => GetMessage("SEF_MODE"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
            "REFRESH" => "Y",
        ),
        "SEF_FOLDER" => array(
            "PARENT" => "SEF_SETTINGS",
            "NAME" => GetMessage("SEF_FOLDER"),
            "TYPE" => "STRING",
            "DEFAULT" => "",
        ),
        "SECTION_URL" => array(
            "PARENT" => "URL_SETTINGS",
            "NAME" => GetMessage("SECTION_URL"),
            "TYPE" => "STRING",
            "DEFAULT" => "",
        ),
        "DETAIL_URL" => array(
            "PARENT" => "URL_SETTINGS",
            "NAME" => GetMessage("DETAIL_URL"),
            "TYPE" => "STRING",
            "DEFAULT" => "",
        ),
        "ELEMENT_URL" => array(
            "PARENT" => "URL_SETTINGS",
            "NAME" => GetMessage("ELEMENT_URL"),
            "TYPE" => "STRING",
            "DEFAULT" => "",
        ),
        "IBLOCK_TYPE" => array(
            "PARENT" => "DATA_SOURCE",
            "NAME" => GetMessage("IBLOCK_TYPE"),
            "TYPE" => "LIST",
            "VALUES" => $arIBlockType,
            "REFRESH" => "Y",
        ),
        "IBLOCK_ID" => array(
            "PARENT" => "DATA_SOURCE",
            "NAME" => GetMessage("IBLOCK_ID"),
            "TYPE" => "LIST",
            "VALUES" => $arIBlock,
            "REFRESH" => "Y",
            "ADDITIONAL_VALUES" => "Y",
        ),
        "SECTION_ID" => array(
            "PARENT" => "DATA_SOURCE",
            "NAME" => GetMessage("SECTION_ID"),
            "TYPE" => "STRING",
            "DEFAULT" => "={$_REQUEST["SECTION_ID"]}",
        ),
        "SECTION_CODE" => array(
            "PARENT" => "DATA_SOURCE",
            "NAME" => GetMessage("SECTION_CODE"),
            "TYPE" => "STRING",
            "DEFAULT" => "={$_REQUEST["SECTION_CODE"]}",
        ),
        "SECTION_USER_FIELDS" => array(
            "PARENT" => "DATA_SOURCE",
            "NAME" => GetMessage("SECTION_USER_FIELDS"),
            "TYPE" => "LIST",
            "MULTIPLE" => "Y",
            "VALUES" => $arUserFields,
            "ADDITIONAL_VALUES" => "Y",
        ),
        "ELEMENT_SORT_FIELD" => array(
            "PARENT" => "SORT_SETTINGS",
            "NAME" => GetMessage("ELEMENT_SORT_FIELD"),
            "TYPE" => "LIST",
            "VALUES" => $arSort,
            "DEFAULT" => "sort",
            "ADDITIONAL_VALUES" => "Y",
        ),
        "ELEMENT_SORT_ORDER" => array(
            "PARENT" => "SORT_SETTINGS",
            "NAME" => GetMessage("ELEMENT_SORT_ORDER"),
            "TYPE" => "LIST",
            "VALUES" => array(
                "asc" => GetMessage("SORT_ASC"),
                "desc" => GetMessage("SORT_DESC"),
            ),
            "DEFAULT" => "asc",
            "ADDITIONAL_VALUES" => "Y",
        ),
        "ELEMENT_SORT_FIELD2" => array(
            "PARENT" => "SORT_SETTINGS",
            "NAME" => GetMessage("ELEMENT_SORT_FIELD2"),
            "TYPE" => "LIST",
            "VALUES" => $arSort,
            "DEFAULT" => "id",
            "ADDITIONAL_VALUES" => "Y",
        ),
        "ELEMENT_SORT_ORDER2" => array(
            "PARENT" => "SORT_SETTINGS",
            "NAME" => GetMessage("ELEMENT_SORT_ORDER2"),
            "TYPE" => "LIST",
            "VALUES" => array(
                "asc" => GetMessage("SORT_ASC"),
                "desc" => GetMessage("SORT_DESC"),
            ),
            "DEFAULT" => "desc",
            "ADDITIONAL_VALUES" => "Y",
        ),
        "FILTER_NAME" => array(
            "PARENT" => "DATA_SOURCE",
            "NAME" => GetMessage("FILTER_NAME"),
            "TYPE" => "STRING",
            "DEFAULT" => "",
        ),
        "INCLUDE_SUBSECTIONS" => array(
            "PARENT" => "DATA_SOURCE",
            "NAME" => GetMessage("INCLUDE_SUBSECTIONS"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "Y",
        ),
        "SHOW_ALL_WO_SECTION" => array(
            "PARENT" => "DATA_SOURCE",
            "NAME" => GetMessage("SHOW_ALL_WO_SECTION"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "CACHE_TYPE" => array(
            "PARENT" => "CACHE_SETTINGS",
            "NAME" => GetMessage("CACHE_TYPE"),
            "TYPE" => "LIST",
            "VALUES" => array(
                "A" => GetMessage("CACHE_TYPE_AUTO"),
                "Y" => GetMessage("CACHE_TYPE_YES"),
                "N" => GetMessage("CACHE_TYPE_NO"),
            ),
            "DEFAULT" => "A",
        ),
        "CACHE_TIME" => array(
            "PARENT" => "CACHE_SETTINGS",
            "NAME" => GetMessage("CACHE_TIME"),
            "TYPE" => "STRING",
            "DEFAULT" => "36000000",
        ),
        "CACHE_GROUPS" => array(
            "PARENT" => "CACHE_SETTINGS",
            "NAME" => GetMessage("CACHE_GROUPS"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "Y",
        ),
        "SET_TITLE" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("SET_TITLE"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "Y",
        ),
        "SET_BROWSER_TITLE" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("SET_BROWSER_TITLE"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "Y",
        ),
        "SET_META_KEYWORDS" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("SET_META_KEYWORDS"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "Y",
        ),
        "SET_META_DESCRIPTION" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("SET_META_DESCRIPTION"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "Y",
        ),
        "SET_LAST_MODIFIED" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("SET_LAST_MODIFIED"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "MESSAGE_404" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("MESSAGE_404"),
            "TYPE" => "STRING",
            "DEFAULT" => "",
        ),
        "SET_STATUS_404" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("SET_STATUS_404"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "SHOW_404" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("SHOW_404"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "FILE_404" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("FILE_404"),
            "TYPE" => "STRING",
            "DEFAULT" => "",
        ),
        "DISPLAY_COMPARE" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("DISPLAY_COMPARE"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "PAGE_ELEMENT_COUNT" => array(
            "PARENT" => "VISUAL",
            "NAME" => GetMessage("PAGE_ELEMENT_COUNT"),
            "TYPE" => "STRING",
            "DEFAULT" => "20",
        ),
        "LINE_ELEMENT_COUNT" => array(
            "PARENT" => "VISUAL",
            "NAME" => GetMessage("LINE_ELEMENT_COUNT"),
            "TYPE" => "STRING",
            "DEFAULT" => "3",
        ),
        "PROPERTY_CODE" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("PROPERTY_CODE"),
            "TYPE" => "LIST",
            "MULTIPLE" => "Y",
            "VALUES" => $arProperty,
            "ADDITIONAL_VALUES" => "Y",
        ),
        "OFFERS_LIMIT" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("OFFERS_LIMIT"),
            "TYPE" => "STRING",
            "DEFAULT" => "5",
        ),
        "SECTION_ID_VARIABLE" => array(
            "PARENT" => "URL_SETTINGS",
            "NAME" => GetMessage("SECTION_ID_VARIABLE"),
            "TYPE" => "STRING",
            "DEFAULT" => "SECTION_ID",
        ),
        "AJAX_MODE" => array(
            "PARENT" => "AJAX_SETTINGS",
            "NAME" => GetMessage("AJAX_MODE"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "AJAX_OPTION_JUMP" => array(
            "PARENT" => "AJAX_SETTINGS",
            "NAME" => GetMessage("AJAX_OPTION_JUMP"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "AJAX_OPTION_STYLE" => array(
            "PARENT" => "AJAX_SETTINGS",
            "NAME" => GetMessage("AJAX_OPTION_STYLE"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "Y",
        ),
        "AJAX_OPTION_HISTORY" => array(
            "PARENT" => "AJAX_SETTINGS",
            "NAME" => GetMessage("AJAX_OPTION_HISTORY"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "AJAX_OPTION_ADDITIONAL" => array(
            "PARENT" => "AJAX_SETTINGS",
            "NAME" => GetMessage("AJAX_OPTION_ADDITIONAL"),
            "TYPE" => "STRING",
            "DEFAULT" => "",
        ),
        "CACHE_FILTER" => array(
            "PARENT" => "CACHE_SETTINGS",
            "NAME" => GetMessage("CACHE_FILTER"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "Y",
        ),
        "CACHE_USE_TAGS" => array(
            "PARENT" => "CACHE_SETTINGS",
            "NAME" => GetMessage("CACHE_USE_TAGS"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "USE_MAIN_ELEMENT_SECTION" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("USE_MAIN_ELEMENT_SECTION"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "ACTION_VARIABLE" => array(
            "PARENT" => "URL_SETTINGS",
            "NAME" => GetMessage("ACTION_VARIABLE"),
            "TYPE" => "STRING",
            "DEFAULT" => "action",
        ),
        "PRODUCT_ID_VARIABLE" => array(
            "PARENT" => "URL_SETTINGS",
            "NAME" => GetMessage("PRODUCT_ID_VARIABLE"),
            "TYPE" => "STRING",
            "DEFAULT" => "id",
        ),
        "PRICE_CODE" => array(
            "PARENT" => "PRICES",
            "NAME" => GetMessage("PRICE_CODE"),
            "TYPE" => "LIST",
            "MULTIPLE" => "Y",
            "VALUES" => $arPrice,
        ),
        "USE_PRICE_COUNT" => array(
            "PARENT" => "PRICES",
            "NAME" => GetMessage("USE_PRICE_COUNT"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
            "REFRESH" => "Y",
        ),
        "SHOW_PRICE_COUNT" => array(
            "PARENT" => "PRICES",
            "NAME" => GetMessage("SHOW_PRICE_COUNT"),
            "TYPE" => "STRING",
            "DEFAULT" => "1",
        ),
        "PRICE_VAT_INCLUDE" => array(
            "PARENT" => "PRICES",
            "NAME" => GetMessage("PRICE_VAT_INCLUDE"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "Y",
        ),
        "CONVERT_CURRENCY" => array(
            "PARENT" => "PRICES",
            "NAME" => GetMessage("CONVERT_CURRENCY"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
            "REFRESH" => "Y",
        ),
        "CURRENCY_ID" => array(
            "PARENT" => "PRICES",
            "NAME" => GetMessage("CURRENCY_ID"),
            "TYPE" => "LIST",
            "VALUES" => $arCurrency,
            "DEFAULT" => "USD",
            "ADDITIONAL_VALUES" => "Y",
        ),
        "BASKET_URL" => array(
            "PARENT" => "URL_SETTINGS",
            "NAME" => GetMessage("BASKET_URL"),
            "TYPE" => "STRING",
            "DEFAULT" => "/basket/",
        ),
        "USE_PRODUCT_QUANTITY" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("USE_PRODUCT_QUANTITY"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "PRODUCT_QUANTITY_VARIABLE" => array(
            "PARENT" => "URL_SETTINGS",
            "NAME" => GetMessage("PRODUCT_QUANTITY_VARIABLE"),
            "TYPE" => "STRING",
            "DEFAULT" => "quantity",
        ),
        "ADD_PROPERTIES_TO_BASKET" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("ADD_PROPERTIES_TO_BASKET"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "Y",
        ),
        "PRODUCT_PROPS_VARIABLE" => array(
            "PARENT" => "URL_SETTINGS",
            "NAME" => GetMessage("PRODUCT_PROPS_VARIABLE"),
            "TYPE" => "STRING",
            "DEFAULT" => "prop",
        ),
        "PARTIAL_PRODUCT_PROPERTIES" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("PARTIAL_PRODUCT_PROPERTIES"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "PRODUCT_PROPERTIES" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("PRODUCT_PROPERTIES"),
            "TYPE" => "LIST",
            "MULTIPLE" => "Y",
            "VALUES" => $arProperty,
            "ADDITIONAL_VALUES" => "Y",
        ),
        "ADD_TO_BASKET_ACTION" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("ADD_TO_BASKET_ACTION"),
            "TYPE" => "LIST",
            "MULTIPLE" => "Y",
            "VALUES" => array(
                "ADD" => GetMessage("ADD_TO_BASKET_ACTION_ADD"),
                "BUY" => GetMessage("ADD_TO_BASKET_ACTION_BUY"),
            ),
            "DEFAULT" => "ADD",
        ),
        "SHOW_TOP_ELEMENTS" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("SHOW_TOP_ELEMENTS"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "SECTION_COUNT_ELEMENTS" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("SECTION_COUNT_ELEMENTS"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "SECTION_TOP_DEPTH" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("SECTION_TOP_DEPTH"),
            "TYPE" => "STRING",
            "DEFAULT" => "2",
        ),
        "SECTIONS_SHOW_PARENT_NAME" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("SECTIONS_SHOW_PARENT_NAME"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "Y",
        ),
        "SECTIONS_HIDE_SECTION_NAME" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("SECTIONS_HIDE_SECTION_NAME"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "SHOW_SECTION_NAME" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("SHOW_SECTION_NAME"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "Y",
        ),
        "SHOW_SECTION_PREVIEW_DESCRIPTION" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("SHOW_SECTION_PREVIEW_DESCRIPTION"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "Y",
        ),
        "SHOW_SECTION" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("SHOW_SECTION"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "Y",
        ),
        "SHOW_SECTION_BANNER" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("SHOW_SECTION_BANNER"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "SHOW_SECTION_DESCRIPTION" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("SHOW_SECTION_DESCRIPTION"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "Y",
        ),
        "SHOW_SECTION_DESCRIPTION_PREVIEW" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("SHOW_SECTION_DESCRIPTION_PREVIEW"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "SHOW_SECTION_ELEMENTS" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("SHOW_SECTION_ELEMENTS"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "Y",
        ),
        "SHOW_SECTION_ELEMENTS_PREVIEW" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("SHOW_SECTION_ELEMENTS_PREVIEW"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "SHOW_SECTION_SORT" => array(
            "PARENT" => "DETAIL_SETTINGS",
            "NAME" => GetMessage("SHOW_SECTION_SORT"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "DISPLAY_TOP_PAGER" => array(
            "PARENT" => "NAVIGATION",
            "NAME" => GetMessage("DISPLAY_TOP_PAGER"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "DISPLAY_BOTTOM_PAGER" => array(
            "PARENT" => "NAVIGATION",
            "NAME" => GetMessage("DISPLAY_BOTTOM_PAGER"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "Y",
        ),
        "PAGER_TEMPLATE" => array(
            "PARENT" => "NAVIGATION",
            "NAME" => GetMessage("PAGER_TEMPLATE"),
            "TYPE" => "STRING",
            "DEFAULT" => "main",
        ),
        "PAGER_SHOW_ALWAYS" => array(
            "PARENT" => "NAVIGATION",
            "NAME" => GetMessage("PAGER_SHOW_ALWAYS"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "PAGER_DESC_NUMBERING" => array(
            "PARENT" => "NAVIGATION",
            "NAME" => GetMessage("PAGER_DESC_NUMBERING"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "PAGER_DESC_NUMBERING_CACHE_TIME" => array(
            "PARENT" => "NAVIGATION",
            "NAME" => GetMessage("PAGER_DESC_NUMBERING_CACHE_TIME"),
            "TYPE" => "STRING",
            "DEFAULT" => "36000",
        ),
        "PAGER_SHOW_ALL" => array(
            "PARENT" => "NAVIGATION",
            "NAME" => GetMessage("PAGER_SHOW_ALL"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "PAGER_BASE_LINK_ENABLE" => array(
            "PARENT" => "NAVIGATION",
            "NAME" => GetMessage("PAGER_BASE_LINK_ENABLE"),
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
    ),
);
?>
