<?php
if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();

$arComponentParameters = array(
    "GROUPS" => array(
        "SETTINGS" => array(
            "NAME" => "Настройки отображения",
            "SORT" => 100,
        ),
        "SEO" => array(
            "NAME" => "SEO настройки",
            "SORT" => 200,
        ),
    ),
    "PARAMETERS" => array(
        "IBLOCK_TYPE" => array(
            "PARENT" => "SETTINGS",
            "NAME" => "Тип инфоблока",
            "TYPE" => "LIST",
            "VALUES" => $arIBlockType,
            "REFRESH" => "Y",
        ),
        "IBLOCK_ID" => array(
            "PARENT" => "SETTINGS",
            "NAME" => "ID инфоблока",
            "TYPE" => "LIST",
            "VALUES" => $arIBlock,
            "REFRESH" => "Y",
            "ADDITIONAL_VALUES" => "Y",
        ),
        "ELEMENT_ID" => array(
            "PARENT" => "SETTINGS",
            "NAME" => "ID элемента",
            "TYPE" => "STRING",
            "DEFAULT" => '={$_REQUEST["ELEMENT_ID"]}',
        ),
        "ELEMENT_CODE" => array(
            "PARENT" => "SETTINGS",
            "NAME" => "Символьный код элемента",
            "TYPE" => "STRING",
            "DEFAULT" => '={$_REQUEST["ELEMENT_CODE"]}',
        ),
        "CHECK_DATES" => array(
            "PARENT" => "SETTINGS",
            "NAME" => "Показывать только активные на данный момент элементы",
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "Y",
        ),
        "FIELD_CODE" => array(
            "PARENT" => "SETTINGS",
            "NAME" => "Поля для выборки",
            "TYPE" => "LIST",
            "MULTIPLE" => "Y",
            "VALUES" => array(
                "ID" => "ID",
                "NAME" => "Название",
                "PREVIEW_TEXT" => "Текст анонса",
                "PREVIEW_PICTURE" => "Картинка анонса",
                "DETAIL_TEXT" => "Детальный текст",
                "DETAIL_PICTURE" => "Детальная картинка",
                "ACTIVE_FROM" => "Дата начала активности",
                "ACTIVE_TO" => "Дата окончания активности",
                "SORT" => "Индекс сортировки",
                "CREATED" => "Дата создания",
                "TIMESTAMP_X" => "Дата изменения",
            ),
            "DEFAULT" => array("ID", "NAME", "PREVIEW_TEXT", "PREVIEW_PICTURE", "DETAIL_TEXT", "DETAIL_PICTURE", "ACTIVE_FROM"),
        ),
        "PROPERTY_CODE" => array(
            "PARENT" => "SETTINGS",
            "NAME" => "Свойства для выборки",
            "TYPE" => "LIST",
            "MULTIPLE" => "Y",
            "VALUES" => $arProperty_LNS,
            "DEFAULT" => array("TAGS", "AUTHOR", "SOURCE"),
        ),
        "IBLOCK_URL" => array(
            "PARENT" => "SEO",
            "NAME" => "URL страницы списка элементов",
            "TYPE" => "STRING",
            "DEFAULT" => "",
        ),
        "USE_PERMISSIONS" => array(
            "PARENT" => "SETTINGS",
            "NAME" => "Учитывать права доступа",
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "GROUP_PERMISSIONS" => array(
            "PARENT" => "SETTINGS",
            "NAME" => "Группы пользователей, имеющие доступ к детальной информации",
            "TYPE" => "LIST",
            "MULTIPLE" => "Y",
            "VALUES" => $arGroup,
            "DEFAULT" => array(1),
            "DEPENDENT_PARAMETERS" => array(
                "USE_PERMISSIONS" => "Y",
            ),
        ),
        "CACHE_TYPE" => array(
            "PARENT" => "SETTINGS",
            "NAME" => "Тип кеширования",
            "TYPE" => "LIST",
            "VALUES" => array(
                "A" => "Авто + Управляемое",
                "Y" => "Кешировать",
                "N" => "Не кешировать",
            ),
            "DEFAULT" => "A",
        ),
        "CACHE_TIME" => array(
            "PARENT" => "SETTINGS",
            "NAME" => "Время кеширования (сек.)",
            "TYPE" => "STRING",
            "DEFAULT" => "36000000",
        ),
        "CACHE_GROUPS" => array(
            "PARENT" => "SETTINGS",
            "NAME" => "Учитывать права доступа",
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "Y",
        ),
        "DISPLAY_TOP_PAGER" => array(
            "PARENT" => "SETTINGS",
            "NAME" => "Выводить над списком",
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "DISPLAY_BOTTOM_PAGER" => array(
            "PARENT" => "SETTINGS",
            "NAME" => "Выводить под списком",
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "PAGER_TEMPLATE" => array(
            "PARENT" => "SETTINGS",
            "NAME" => "Название шаблона",
            "TYPE" => "STRING",
            "DEFAULT" => "",
        ),
        "PAGER_SHOW_ALWAYS" => array(
            "PARENT" => "SETTINGS",
            "NAME" => "Выводить всегда",
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "PAGER_DESC_NUMBERING" => array(
            "PARENT" => "SETTINGS",
            "NAME" => "Использовать обратную навигацию",
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "PAGER_DESC_NUMBERING_CACHE_TIME" => array(
            "PARENT" => "SETTINGS",
            "NAME" => "Время кеширования страниц для обратной навигации",
            "TYPE" => "STRING",
            "DEFAULT" => "36000",
        ),
        "PAGER_SHOW_ALL" => array(
            "PARENT" => "SETTINGS",
            "NAME" => "Показывать ссылку 'Все'",
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "PAGER_BASE_LINK_ENABLE" => array(
            "PARENT" => "SETTINGS",
            "NAME" => "Включить обработку базовых ссылок",
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "N",
        ),
        "PAGER_BASE_LINK" => array(
            "PARENT" => "SETTINGS",
            "NAME" => "Базовые ссылки для постраничной навигации",
            "TYPE" => "STRING",
            "DEFAULT" => "",
        ),
        "PAGER_PARAMS_NAME" => array(
            "PARENT" => "SETTINGS",
            "NAME" => "Имя параметра с номером страницы",
            "TYPE" => "STRING",
            "DEFAULT" => "PAGEN_",
        ),
        "SHOW_SIMILAR_ARTICLES" => array(
            "PARENT" => "SETTINGS",
            "NAME" => "Показывать похожие статьи",
            "TYPE" => "CHECKBOX",
            "DEFAULT" => "Y",
        ),
        "SIMILAR_ARTICLES_COUNT" => array(
            "PARENT" => "SETTINGS",
            "NAME" => "Количество похожих статей",
            "TYPE" => "STRING",
            "DEFAULT" => "3",
        ),
    ),
);
